import { definePlugin } from '@nova/plugins';
import fs from 'fs';
import path from 'path';

export interface SeoOptimizeOptions {
  title?: string;
  description?: string;
  image?: string;
  url?: string;
}

export const seoOptimizePlugin = (options: SeoOptimizeOptions = {}) => {
  return definePlugin({
    name: 'nova-seo-optimize',
    version: '1.0.0',

    /**
     * Hook 1: beforeCompile
     * Quét tất cả các file source code trước khi biên dịch sang JS, tự động thay thế
     * __APP_VERSION__ và __BUILD_TIME__ thành giá trị thực tế của thời điểm build.
     */
    beforeCompile(code, ctx) {
      try {
        const pkgPath = path.resolve('./package.json');
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
        
        // Lấy mốc giờ Việt Nam hiện tại
        const buildTime = new Date().toLocaleString('vi-VN', { 
          timeZone: 'Asia/Ho_Chi_Minh',
          hour12: false
        });

        // Thực hiện thay thế trực tiếp
        return code
          .replace(/__APP_VERSION__/g, pkg.version || '0.1.0')
          .replace(/__BUILD_TIME__/g, buildTime);
      } catch (err: any) {
        console.error('[SEO-Optimize] Error reading package.json:', err.message);
      }
      return null;
    },

    /**
     * Hook 2: afterSSR (Compile-time HTML transformation)
     * Nhận chuỗi HTML trong bộ nhớ đệm, tự động chèn đầy đủ thẻ Meta OG (Open Graph)
     * hỗ trợ SEO, sau đó thực hiện thu nhỏ (minify) file HTML.
     * 
     * Hoạt động cực nhanh trong cả chế độ DEV SERVER và PRODUCTION BUILD!
     */
    afterSSR(html, ctx) {
      console.log(`📝 [SEO-Optimize] Đang xử lý HTML thời gian thực (${ctx.env} mode)...`);

      // Định nghĩa khối thẻ Meta chất lượng cao
      const metaTags = `
  <!-- SEO & Open Graph Tags (Auto-generated by Nova SEO Plugin) -->
  <title>${options.title || 'Nova Framework App'}</title>
  <meta name="description" content="${options.description || 'A next-generation signals-based web application.'}">
  <meta property="og:title" content="${options.title || 'Nova Framework App'}">
  <meta property="og:description" content="${options.description || 'A next-generation signals-based web application.'}">
  ${options.image ? `<meta property="og:image" content="${options.image}">` : ''}
  ${options.url ? `<meta property="og:url" content="${options.url}">` : ''}
  <meta property="og:type" content="website">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="canonical" href="${options.url || ''}">
      `;

      // Loại bỏ các thẻ title và description mặc định nếu có trong tệp gốc
      let optimizedHtml = html.replace(/<title>.*?<\/title>/gi, '');
      optimizedHtml = optimizedHtml.replace(/<meta name="description".*?>/gi, '');
      
      // Inject khối Meta chất lượng cao ngay sau thẻ <head>
      optimizedHtml = optimizedHtml.replace('<head>', `<head>${metaTags}`);

      // Thực hiện tối ưu hóa cấu trúc tệp HTML (Minification)
      const originalSize = Buffer.byteLength(optimizedHtml, 'utf8');
      
      optimizedHtml = optimizedHtml
        .replace(/<!--[\s\S]*?-->/g, '')     // Xóa bỏ chú thích
        .replace(/\s+/g, ' ')                  // Thu gọn khoảng trắng
        .replace(/>\s+</g, '><');              // Xóa khoảng trắng thừa giữa tag

      const minifiedSize = Buffer.byteLength(optimizedHtml, 'utf8');
      const savedPercent = (((originalSize - minifiedSize) / originalSize) * 100).toFixed(1);

      console.log(`✅ [SEO-Optimize] HTML được tối ưu thành công! Tiết kiệm: ${originalSize} B -> ${minifiedSize} B (-${savedPercent}%)`);
      
      return optimizedHtml;
    }
  });
};
